locale: "en-US"
title: "Ming Zhao"
title_separator: "-"
name: "Ming Zhao"
description: "Ming Zhao's academic homepage"
url: "https://minz328.github.io"
baseurl: ""
repository: "minz328/minz328.github.io"
theme: null

author:
  name: "Ming Zhao"
  avatar: "myavatar_v3.jpg"
  role: "Graduate Research Assistant"
  department: "School of Computing"
  institution: "University of Nebraska-Lincoln"
  email: "mzhao7@huskers.unl.edu"
  googlescholar: "https://scholar.google.com/citations?user=VdsvDfUAAAAJ&hl=en&oi=sra"
  linkedin: "ming-zhao-"
  research_interests:
    - "AI for Wireless Networks"
    - "Network Automation"
    - "Reinforcement Learning"
    - "Edge Computing"

social:
  type: "Person"
  name: "Ming Zhao"
  links:
    - "https://www.linkedin.com/in/ming-zhao-"
    - "https://scholar.google.com/citations?user=VdsvDfUAAAAJ&hl=en&oi=sra"

include:
  - _pages

exclude:
  - .DS_Store
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - assets/.DS_Store
  - node_modules
  - vendor

markdown: kramdown

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

sass:
  style: compressed

timezone: America/Chicago

plugins:
  - jekyll-sitemap
