locale: "en-US"
title: "My Homepage"
title_separator: "-"
name: "Ming Zhao"
description: "Ming Zhao's academic homepage"
url: "https://minz328.github.io"
baseurl: ""
repository: "minz328/minz328.github.io"
og_image: "site-logo.png"
theme: null

author:
  name: "Ming Zhao"
  avatar: "myavatar_v3.jpg"
  role: "Graduate Research Assistant"
  department: "School of Computing"
  institution: "University of Nebraska-Lincoln"
  email: "mzhao7@huskers.unl.edu"
  googlescholar: "https://scholar.google.com/citations?user=VdsvDfUAAAAJ&hl=en&oi=sra"
  linkedin: "ming-zhao-"

social:
  type: "Person"
  name: "Ming Zhao"
  links:
    - "https://www.linkedin.com/in/ming-zhao-"
    - "https://scholar.google.com/citations?user=VdsvDfUAAAAJ&hl=en&oi=sra"

include:
  - _pages
  - files

exclude:
  - .DS_Store
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - assets/.DS_Store
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - how_to_modify_locally.txt
  - node_modules
  - package.json
  - vendor

encoding: "utf-8"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

timezone: America/Chicago

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
